### ISSUE TITLE
Cannot declare class CreateUsersTable, because the name is already in use

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Auth#3]
* `composer create-project --prefer-dist laravel/laravel`
* `composer require escolalms/auth` 
* `php artisan migrate` 

```php
Migration table created successfully.
PHP Fatal error:  Cannot declare class CreateUsersTable, because the name is already in use in /var/www/html/host/vendor/escolalms/core/database/migrations/2019_02_18_000001_create_users_table.php on line 7
PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /var/www/html/host/vendor/symfony/error-handler/Error/FatalError.php:37
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/var/www/html/h...', 37, Array)
#1 /var/www/html/host/vendor/symfony/error-handler/Error/FatalError.php(37): xdebug_get_function_stack()
#2 /var/www/html/host/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(143): Symfony\Component\ErrorHandler\Error\FatalError->__construct('Cannot declare ...', 0, Array, 0)
#3 /var/www/html/host/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(130): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalErrorFromPhpError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#5 {main}
  thrown in /var/www/html/host/vendor/symfony/error-handler/Error/FatalError.php on line 37
```

**Comment by qunabu** [comment]
Default Laravel has `user` migrations ...
